# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interfaz.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QGridLayout,
    QGroupBox, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QTextBrowser, QWidget)

class Ui_VentanaPrincipal(object):
    def setupUi(self, VentanaPrincipal):
        if not VentanaPrincipal.objectName():
            VentanaPrincipal.setObjectName(u"VentanaPrincipal")
        VentanaPrincipal.setWindowModality(Qt.WindowModality.ApplicationModal)
        VentanaPrincipal.resize(631, 553)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(203, 203, 203, 179))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 179))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        brush3 = QBrush(QColor(229, 229, 229, 179))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        brush4 = QBrush(QColor(101, 101, 101, 179))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        brush5 = QBrush(QColor(135, 135, 135, 179))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        brush7 = QBrush(QColor(229, 229, 229, 217))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 0, 0, 127))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        brush10 = QBrush(QColor(101, 101, 101, 89))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush2)
#endif
        VentanaPrincipal.setPalette(palette)
        VentanaPrincipal.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.accion_guardar = QAction(VentanaPrincipal)
        self.accion_guardar.setObjectName(u"accion_guardar")
        self.accion_cargar = QAction(VentanaPrincipal)
        self.accion_cargar.setObjectName(u"accion_cargar")
        self.centralwidget = QWidget(VentanaPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.lienzo_arbol = QGraphicsView(self.centralwidget)
        self.lienzo_arbol.setObjectName(u"lienzo_arbol")

        self.gridLayout.addWidget(self.lienzo_arbol, 0, 1, 1, 1)

        self.p_recorridos = QTextBrowser(self.centralwidget)
        self.p_recorridos.setObjectName(u"p_recorridos")
        self.p_recorridos.setMaximumSize(QSize(16777215, 41))

        self.gridLayout.addWidget(self.p_recorridos, 1, 0, 1, 2)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(129, 434))
        font = QFont()
        font.setBold(False)
        self.frame.setFont(font)
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.groupBox = QGroupBox(self.frame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 20, 111, 111))
        palette1 = QPalette()
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        self.groupBox.setPalette(palette1)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.BTarbol_abb = QPushButton(self.groupBox)
        self.BTarbol_abb.setObjectName(u"BTarbol_abb")
        self.BTarbol_abb.setGeometry(QRect(10, 50, 91, 26))
        self.BTarbol_avl = QPushButton(self.groupBox)
        self.BTarbol_avl.setObjectName(u"BTarbol_avl")
        self.BTarbol_avl.setGeometry(QRect(10, 80, 91, 26))
        self.BTarbol_bin = QPushButton(self.groupBox)
        self.BTarbol_bin.setObjectName(u"BTarbol_bin")
        self.BTarbol_bin.setGeometry(QRect(10, 20, 91, 26))
        self.groupBox_2 = QGroupBox(self.frame)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 150, 111, 151))
        self.bt_insertar = QPushButton(self.groupBox_2)
        self.bt_insertar.setObjectName(u"bt_insertar")
        self.bt_insertar.setGeometry(QRect(10, 20, 81, 26))
        self.bt_buscar = QPushButton(self.groupBox_2)
        self.bt_buscar.setObjectName(u"bt_buscar")
        self.bt_buscar.setGeometry(QRect(10, 50, 81, 26))
        self.bt_eliminar = QPushButton(self.groupBox_2)
        self.bt_eliminar.setObjectName(u"bt_eliminar")
        self.bt_eliminar.setGeometry(QRect(10, 80, 81, 26))
        self.entrada_nodo = QSpinBox(self.groupBox_2)
        self.entrada_nodo.setObjectName(u"entrada_nodo")
        self.entrada_nodo.setGeometry(QRect(10, 110, 81, 26))
        self.entrada_nodo.setMinimum(-999)
        self.entrada_nodo.setMaximum(999)
        self.groupBox_3 = QGroupBox(self.frame)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 310, 111, 111))
        self.bt_ino = QPushButton(self.groupBox_3)
        self.bt_ino.setObjectName(u"bt_ino")
        self.bt_ino.setGeometry(QRect(10, 20, 81, 26))
        self.bt_preo = QPushButton(self.groupBox_3)
        self.bt_preo.setObjectName(u"bt_preo")
        self.bt_preo.setGeometry(QRect(10, 50, 81, 26))
        self.bt_posto = QPushButton(self.groupBox_3)
        self.bt_posto.setObjectName(u"bt_posto")
        self.bt_posto.setGeometry(QRect(10, 80, 81, 26))

        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        VentanaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(VentanaPrincipal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 631, 33))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        VentanaPrincipal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(VentanaPrincipal)
        self.statusbar.setObjectName(u"statusbar")
        VentanaPrincipal.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addAction(self.accion_guardar)
        self.menuArchivo.addAction(self.accion_cargar)

        self.retranslateUi(VentanaPrincipal)

        QMetaObject.connectSlotsByName(VentanaPrincipal)
    # setupUi

    def retranslateUi(self, VentanaPrincipal):
        VentanaPrincipal.setWindowTitle(QCoreApplication.translate("VentanaPrincipal", u"MainWindow", None))
        self.accion_guardar.setText(QCoreApplication.translate("VentanaPrincipal", u"Guardar", None))
        self.accion_cargar.setText(QCoreApplication.translate("VentanaPrincipal", u"Cargar", None))
        self.groupBox.setTitle(QCoreApplication.translate("VentanaPrincipal", u"Tipos de \u00e1rboles", None))
        self.BTarbol_abb.setText(QCoreApplication.translate("VentanaPrincipal", u"Arbol ABB", None))
        self.BTarbol_avl.setText(QCoreApplication.translate("VentanaPrincipal", u"Arbol AVL", None))
        self.BTarbol_bin.setText(QCoreApplication.translate("VentanaPrincipal", u"Arbol Binario", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("VentanaPrincipal", u"Operaciones", None))
        self.bt_insertar.setText(QCoreApplication.translate("VentanaPrincipal", u"Insertar", None))
        self.bt_buscar.setText(QCoreApplication.translate("VentanaPrincipal", u"Buscar", None))
        self.bt_eliminar.setText(QCoreApplication.translate("VentanaPrincipal", u"Eliminar", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("VentanaPrincipal", u"Recorridos", None))
        self.bt_ino.setText(QCoreApplication.translate("VentanaPrincipal", u"In-Orden", None))
        self.bt_preo.setText(QCoreApplication.translate("VentanaPrincipal", u"Pre-Orden", None))
        self.bt_posto.setText(QCoreApplication.translate("VentanaPrincipal", u"Post-Orden", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("VentanaPrincipal", u"Archivo", None))
    # retranslateUi

